language: objective-c

env:
  global:
    - secure: f4hgPmIW9fXvgomICcfe7vjJY3TFzALboVq1Nz9xrX1T25oIt7+rHd8CjPbBZvkSgSBY3zDItY5n47kAbWoFZGqmWF9K26WEnljPLab4QeLmy7GGZ7/jCTyashPucc34b5SC2SuXAMbDSSbEImguY27GQmeCnRqpDOS7kDVGZEU=
    - secure: oSMNhXFS6Cb9GLlYaFhqABWDLYcagkz6KY5T6jFzJ6tCLhBSVbdSX9p0RhOBcIV7vZ2WW12Nbl9DTtUgccuQJWZaI504KBq2dD94R54h4hY5ZDymsRLqNZ71fD/gh3dhV9ukciHaPYPK2/N1OSxDSUAeBsZtPJxOprOH07iUNpQ=
  matrix:
    - NODE_VERSION="v0.10"
    - NODE_VERSION="v0.12"
    - NODE_VERSION="iojs-v1.0"
    - NODE_VERSION="iojs-v2.0"

before_install:

  - echo $TRAVIS_OS_NAME

  # commit
  # ------------------------
  # The commit message is used to determine the whether to manually
  # invoke a binary publish

  - COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')

  # node
  # ------------------------

  - export PATH=./node_modules/.bin/:$PATH
  - rm -rf ~/.nvm && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - node --version
  - npm --version
  - nvm --version

  # publish dependencies
  # ------------------------

  - npm install node-gyp -g
  - npm install aws-sdk

install:

  # in the first instance we build from source to create the initial binary
  # which can then be used to create a package

  - npm install --build-from-source
  - npm test

before_script:

  # Detemine if a publish is required.
  #
  # a) we are building a tag
  # b) we put [publish binary] in the commit message

  - PUBLISH_BINARY=false

  - if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;       # a
  - if test "${COMMIT_MESSAGE#*'[publish binary]'}" != "$COMMIT_MESSAGE"; then PUBLISH_BINARY=true; fi; # b

  # package & publish
  # ------------------------

  - if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package publish; fi;

  # clean-up
  # ------------------------

  - node-pre-gyp clean
  - node-gyp clean

script:

  # validate
  # ------------------------
  # Post publishing a release verify that installing will pull down latest
  # binary from remote host

  - INSTALL_RESULT=0
  - if [[ $PUBLISH_BINARY == true ]]; then INSTALL_RESULT=$(npm install --fallback-to-build=false > /dev/null)$? || true; fi;

  - node-pre-gyp clean

  # failure?
  # ------------------------
  # if install returned non zero (errored) then we first unpublish and then
  # call false so travis will bail at this line.

  - if [[ $INSTALL_RESULT != 0 ]]; then node-pre-gyp unpublish; fi;
  - if [[ $INSTALL_RESULT != 0 ]]; then echo "returned $INSTALL_RESULT";false; fi;

after_success:

  # display all published binaries

 - node-pre-gyp info
